version: '3'

services:
    db:
        container_name: pg_db
        build:
            context: ../
            dockerfile: ./.dockerDB/Dockerfile
        env_file:
            - ../.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data:delegated

volumes:
    db-data: